// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxshhcwtuatucdqmiubd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14c2hoY3d0dWF0dWNkcW1pdWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzU4NDAsImV4cCI6MjA1OTkxMTg0MH0.O_ODhUcI424GPuSuCQEiGvDueq9d31pLCwOBCXGHjAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);